//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KelimeUzmani.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleSentence
    {
        public int ID { get; set; }
        public int WordID { get; set; }
        public string Sentence { get; set; }
    
        public virtual Word Word { get; set; }
    }
}
